---

- name: Include required vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - "{{ playbook_dir }}/roles/mig_controller_prereqs/defaults/main.yml"
    - "{{ playbook_dir }}/config/velero_aws_creds.yml"

- name: Deploy mig controller
  import_tasks: deploy.yml

- name: Prepare remote cluster
  import_tasks: prepare_remote_cluster.yml
  when: mig_controller_host_cluster|bool and mig_controller_remote_cluster_online|bool

- name: Process mig controller deployment summary
  import_tasks: summary.yml
  when: mig_controller_host_cluster|bool and mig_controller_remote_cluster_online|bool
